version: '3.8'

networks:
  pgnetwork:
    driver: bridge

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7000:80"
    networks:
      - pgnetwork
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork
    ports:
      - "5444:5432"

volumes:
  pgdata: