"""migration create test model

Revision ID: 405bb1d10bd7
Revises: 6c0a8ac6545a
Create Date: 2024-10-11 01:40:01.634857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405bb1d10bd7'
down_revision = '6c0a8ac6545a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_test',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_test_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_test_email'))

    op.drop_table('users_test')
    op.drop_table('employees_test')
    # ### end Alembic commands ###
