name: Python Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Set up environment variables
      run: |
        echo "JWT_SECRET=test_secret_key" >> $GITHUB_ENV

    - name: Run pytest
      env:
        DATABASE_URL: ${{ secrets.DB_URI }}  # Ensure this is securely stored in GitHub Secrets
      run: |
        poetry run pytest -s -vvv --cov --cov-fail-under=70 --cov-report=term-missing

    - name: Upload pytest results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: ./tests/.pytest_cache
